import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import 'react-loading-skeleton/dist/skeleton.css'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/Toggle'
import { NavBar } from '@/components/NavBar'
import { Provider } from '@/components/Provider'
import 'simplebar-react/dist/simplebar.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        'min-h-screen font-sans antialiased grainy',
        inter.className
      )}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <Provider>
          <NavBar />
          {children}
        </Provider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}